# Pipeline to trigger three individual pipelines from a self-hosted agent
name: TriggerThreePipelines
trigger:
  - none
pr:
  - none
resources:
  pipelines:
    - pipeline: Pipeline1
      project: aks-devops-project
      source: prod-aks-project-CI
      trigger:
        branches:
          include:
            - main
    - pipeline: Pipeline2
      project: aks-devops-project
      source: dev-aks-project-CI
      trigger:
        branches:
          include:
            - dev
jobs:
  - job: TriggerPipelines
    pool:
      name: alokeagent
    steps:
      - task: TriggerBuild@1
        inputs:
          buildType: 'specificBuild'
          project: aks-devops-project
          pipeline: $(Pipeline1.pipelineId)
          version: 'latest'
          waitOnBuild: true
        displayName: 'Trigger Pipeline1'
      - task: TriggerBuild@2
        inputs:
          buildType: 'specificBuild'
          project: aks-devops-project
          pipeline: $(Pipeline2.pipelineId)
          version: 'latest'
          waitOnBuild: true
        displayName: 'Trigger Pipeline2'
    dependsOn: 
      - Pipeline1
      - Pipeline2


