# Pipeline to trigger three individual pipelines from a self-hosted agent
name: TriggerThreePipelines
trigger:
  - none
pr:
  - none
variables:
  - group: <variable_group_name>
resources:
  pipelines:
    - pipeline: Pipeline1
      project: aks-devops-project
      source: prod-aks-project-CI
      trigger:
        branches:
          include:
            - main
    - pipeline: Pipeline2
      project: aks-devops-project
      source: dev-aks-project-CI
      trigger:
        branches:
          include:
            - dev
    - pipeline: Pipeline3
      project: aks-devops-project
      source: qa-aks-project-CI
      trigger:
        branches:
          include:
            - qa
jobs:
  - job: TriggerPipelines
    pool:
      name: alokeagent
    steps:
      - task: TriggerBuild
        inputs:
          buildType: 'specificBuild'
          project: aks-devops-project
          pipeline: $(Pipeline1.pipelineId)
          version: 'latest'
          waitOnBuild: true
        displayName: 'Trigger Pipeline1'
      - task: TriggerBuild
        inputs:
          buildType: 'specificBuild'
          project: aks-devops-project
          pipeline: $(Pipeline2.pipelineId)
          version: 'latest'
          waitOnBuild: true
        displayName: 'Trigger Pipeline2'
      - task: TriggerBuild
        inputs:
          buildType: 'specificBuild'
          project: aks-devops-project
          pipeline: $(Pipeline3.pipelineId)
          version: 'latest'
          waitOnBuild: true
        displayName: 'Trigger Pipeline3'
    dependsOn: 
      - Pipeline1
      - Pipeline2
      - Pipeline3

