# Pipeline to trigger three individual pipelines from a self-hosted agent
name: TriggerThreePipelines
trigger:
  - none
pr:
  - none
resources:
  pipelines:
    - pipeline: Pipeline1
      project: aks-devops-project
      source: prod-aks-project-CI
      trigger:
        branches:
          include:
            - main
jobs:
  - job: TriggerPipelines
    pool:
      name: alokeagent
    steps:
      - task: AzureDevOpsTask@1
        inputs:
          azureSubscriptionEndpoint: <azure_subscription_endpoint_name>
          scriptType: PowerShell
          scriptLocation: inlineScript
          inlineScript: |
            $token = "$(System.AccessToken)"
            $url = "$(System.CollectionUri)"
            $headers = @{ Authorization = "Bearer $token" }
            $body = @{
              definition = $(Pipeline1.pipelineId)
              parameters = @{ }
              resources = @{ repositories = @{ self = @{ refName = 'refs/heads/main' } } } }
            }
            Invoke-RestMethod -Uri "$url/_apis/pipelines/pipelineRuns?api-version=6.0-preview" -Method Post -Headers $headers -Body ($body | ConvertTo-Json -Depth 5)
        displayName: 'Trigger Pipeline1'
    dependsOn: 
      - Pipeline1
 


